### ISSUE TITLE
how to participate?

### ISSUE THREAD

**Issue by nicolasdb** [softrevolter/fab.deposit.BXL#1]
Hi, 
That's so a nice idea to have a shared repository to work on this. 👍 

>this is me trying to comment an issue without to be on any team or having any editing right on this repository. 

>Will it work....? :)

**Comment by softrevolter** [comment]
It looked like it worked. Yes use this as a sdrafr

**Comment by nicolasdb** [comment]
yes, c'est cool. 
Je vais rédiger ma dernière idée de checklist pour les super User. 
à tout de suite :)
